
services:

  orb-app-local:
    image: orb-app-local
    profiles: 
      - all
      - testing
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_BE_API_URL: http://localhost:${API_SERVICE_PORT}
      PORT: 3000
    ports:
      - ${ORB_PORT}:3000

  api-service-local:
    image: api-service-local
    profiles: 
      - all
      - python-src
      - dev
    build:
      context: ./backend/service-api
      dockerfile: ServiceDockerfile
    environment:
      - DB_HOST=host.docker.internal:${DB_PORT}
      - CORE_DB_USER=${ORBSIGHT_CORE_USER}
      - CORE_DB_PASSWORD=${ORBSIGHT_CORE_PASSWORD}
      - CUBEJS_API_ENDPOINT=http://host.docker.internal:${CUBEJS_PORT}/cubejs-api/v1/load
      - PREFECT_DB_NAME=${PREFECT_DB}
      - PREFECT_DB_USER=${PREFECT_USER}
      - PREFECT_DB_PASSWORD=${PREFECT_PASSWORD}
      - PREFECT_API_URL=http://host.docker.internal:${PREFECT_PORT}/api
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OUTSCRAPPER_API_KEY=${OUTSCRAPPER_API_KEY}
      - SPACEPULSE_URL=http://host.docker.internal:3001/capAm/enquiry/partner
      - SPACEPULSE_API_KEY=${SPACEPULSE_API_KEY}
      - SPACEPULSE_API_SECRET=${SPACEPULSE_API_SECRET}
      - APP_NAME=service
      - ORB_URL=http://localhost:${ORB_PORT}
      - COOKIE_SECURE=${COOKIE_SECURE}
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - ${API_SERVICE_PORT}:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"

  database:
    image: postgres:14
    profiles: 
      - all
      - postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./postgres-db/postgres-data:/var/lib/postgresql/data
      - ./postgres-db/db-init:/docker-entrypoint-initdb.d


  redis:
    image: redis:6
    profiles: 
      - all
      - dev
    ports:
      - ${REDIS_PORT}:6379
      # Host:Container

  cube:
    image: cubejs/cube:v0.36.3
    profiles: 
      - all
      - dev
    ports:
      - ${CUBEJS_PORT}:4000
    env_file:
      - backend/cubejs/.env
    environment:
      - CUBEJS_DEV_MODE=true
      - CUBEJS_DB_TYPE=postgres
      - CUBEJS_DB_HOST=172.17.0.1
      - CUBEJS_DB_PORT=${DB_PORT}
      - CUBEJS_DB_USER=${ORBSIGHT_TENANT_USER}
      - CUBEJS_DB_PASS=${ORBSIGHT_TENANT_PASSWORD}
      - CUBEJS_DB_SSL=true
      # - CUBEJS_DB_NAME=orb_tenant_playarena
    volumes:
      - ./backend/cubejs/model:/cube/conf/model
  
  prefect-server:
    image: prefecthq/prefect:3-python3.11
    profiles: 
      - all
      - prefect
    restart: always
    # volumes:
    #   - prefect:/root/.prefect
    entrypoint: ["/opt/prefect/entrypoint.sh", "prefect", "server", "start"]
    environment:
      - PREFECT_UI_URL=http://127.0.0.1:${PREFECT_PORT}/api
      - PREFECT_API_URL=http://127.0.0.1:${PREFECT_PORT}/api
      # If you want to access Prefect Server UI from anywhere other than the Docker host machine, you will need to change
      # PREFECT_UI_URL and PREFECT_API_URL to match the external hostname/IP of the host machine. For example:
      #- PREFECT_UI_URL=http://external-ip:4200/api
      #- PREFECT_API_URL=http://external-ip:4200/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://${PREFECT_USER}:${PREFECT_PASSWORD}@host.docker.internal:${DB_PORT}/${PREFECT_DB}
      # Uncomment the following line if you want to use the 'S3 Bucket' storage block instead of the older 'S3' storage
      # - EXTRA_PIP_PACKAGES=prefect-aws
    ports:
      - ${PREFECT_PORT}:4200
    extra_hosts:
      - "host.docker.internal:host-gateway"

  worker-service-local:
    image: worker-service-local
    profiles: 
      - all
      - python-src
      - prefect
      - worker
      - dev
    build:
      context: ./backend/service-api
      dockerfile: WorkerDockerfile
    environment:
      - DB_HOST=host.docker.internal:${DB_PORT}
      - CORE_DB_USER=${ORBSIGHT_CORE_USER}
      - CORE_DB_PASSWORD=${ORBSIGHT_CORE_PASSWORD}
      - PREFECT_API_URL=http://host.docker.internal:${PREFECT_PORT}/api
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OUTSCRAPPER_API_KEY=${OUTSCRAPPER_API_KEY}
      - SPACEPULSE_URL=http://host.docker.internal:3001/capAm/enquiry/partner
      - SPACEPULSE_API_KEY=${SPACEPULSE_API_KEY}
      - SPACEPULSE_API_SECRET=${SPACEPULSE_API_SECRET}
      - APP_NAME=prefect-workers
      - REDIS_PORT=${REDIS_PORT}
    extra_hosts:
      - "host.docker.internal:host-gateway"

