-- Prefect
CREATE DATABASE ${PREFECT_DB};
CREATE USER ${PREFECT_USER} WITH ENCRYPTED PASSWORD '${PREFECT_PASSWORD}';
GRANT ALL PRIVILEGES ON DATABASE ${PREFECT_DB} TO ${PREFECT_USER};

-- Core DB
CREATE DATABASE orb_core;
CREATE USER ${ORBSIGHT_CORE_USER} WITH ENCRYPTED PASSWORD '${ORBSIGHT_CORE_PASSWORD}';
GRANT ALL PRIVILEGES ON DATABASE orb_core TO ${ORBSIGHT_CORE_USER};

-- Tenant
CREATE USER ${ORBSIGHT_TENANT_USER} WITH ENCRYPTED PASSWORD '${ORBSIGHT_TENANT_PASSWORD}';


