import datetime

from obsei.payload import TextPayload


def get_android_payload():
    return [
        TextPayload(segmented_data={}, meta={
            'reviewId': 'gp:AOqpTOGzOzevMrhvuCL_G5jtA56NtyrT_LGONKzQAIX0E4CcN6s18gLTfOeFfBaZVPWkBl39K8Up1gVFDeJJ53U',
            'userName': 'Sivarama Krishnan',
            'userImage': 'https://play-lh.googleusercontent.com/a-/AOh14GiTD4CE5bi0VZxkluvK77vZwiIxG_cIZTrS3lWRjW4',
            'content': "Couldn't login for past 6 months... The abv review I sent 2 months before. Till now I'm not able to use the app. There is no response from BOI. No one knows the issue. Finally I found the issue, the app is not supported in Android 11. Kindly update your app to Android 11 (oxygen os).",
            'score': 1, 'thumbsUpCount': 0, 'reviewCreatedVersion': '1.1.41',
            'at': datetime.datetime(2022, 4, 4, 0, 18, 11), 'replyContent': None, 'repliedAt': None},
                    source_name='PlayStoreScrapper',
                    processed_text="Couldn't login for past 6 months... The abv review I sent 2 months before. Till now I'm not able to use the app. There is no response from BOI. No one knows the issue. Finally I found the issue, the app is not supported in Android 11. Kindly update your app to Android 11 (oxygen os)."),
        TextPayload(segmented_data={}, meta={
            'reviewId': 'gp:AOqpTOFInGnL1z0cdoTQYPI88wQdc0Q40n0Hr7htslSIr79R5-PSDe7tD2Y7y1uLNG5BpmCf0IlDBWMqsNNnxhg',
            'userName': 'Himanshu Singhania',
            'userImage': 'https://play-lh.googleusercontent.com/a-/AOh14GgqZjXLWESjaoA9DsExDXp9appQGLhpkkXU70gTgQ',
            'content': 'Totally low grade app. Need much improvement. Make it smoother and give it a fresh and attractive look. Add more features like to order physical atm card via mobile banking as well as internet banking. You can take the example of "bob world, AU bank, IDFC First Bank and many more mobile banking applications. It\'s not so useful now. Totally disliked it..',
            'score': 1, 'thumbsUpCount': 12, 'reviewCreatedVersion': '1.1.36',
            'at': datetime.datetime(2022, 4, 3, 21, 40, 13),
            'replyContent': 'Hi Himanshu Singhania, We are working to give you a better experience in next upgrade. Stay tuned! Do not share your account no. & card details such as card number, CVV, expiry and PIN, mobile app & internet banking login credentials with anyone. Happy Banking! Team BOI',
            'repliedAt': datetime.datetime(2022, 2, 19, 13, 11, 38)}, source_name='PlayStoreScrapper',
                    processed_text='Totally low grade app. Need much improvement. Make it smoother and give it a fresh and attractive look. Add more features like to order physical atm card via mobile banking as well as internet banking. You can take the example of "bob world, AU bank, IDFC First Bank and many more mobile banking applications. It\'s not so useful now. Totally disliked it..'),
        TextPayload(segmented_data={}, meta={
            'reviewId': 'gp:AOqpTOHQQSgqhf7c5x94N0V_TdK8JZt6qDA32wtSQUKuc6Z-dZBF9Ka5sdufli2WYMmMJfpkwVZn9Qp6Ii99tLg',
            'userName': 'Shivram Mukhi',
            'userImage': 'https://play-lh.googleusercontent.com/a-/AOh14GhpLSYPlkYji9RA9pJflbxjJkyYSQDSnRnwvbga',
            'content': 'Nice', 'score': 5, 'thumbsUpCount': 1, 'reviewCreatedVersion': None,
            'at': datetime.datetime(2022, 4, 3, 21, 23, 59), 'replyContent': None, 'repliedAt': None},
                    source_name='PlayStoreScrapper', processed_text='Nice'), TextPayload(segmented_data={}, meta={
            'reviewId': 'gp:AOqpTOHW4nuQOqFvhz5PVj1PDJMV2KAJ9KPEdaTWzWaaiMfjJMeq1gHgr6TkBm-zAmwFs7fjysV-iv9H1rW2sfA',
            'userName': 'Vivek',
            'userImage': 'https://play-lh.googleusercontent.com/a/AATXAJwwctt2oHAbiCjN-ytz9F085Yhjmcr36T3Wkb_2CA=mo',
            'content': "At least provide basic features of updating email id, Contact number online. Your Server Automatically deleted my email, Now you want me to take one leave and visit to branch for your mistake. Then what's the use of your this app and netbanking. Even small fintech mashroomed have better apps than BOI. Banks backend team's work is not merely to do task, but to check and ensure the effectiveness of performed tasks/Adequacy of provided options and adding more &more convenience to customers.",
            'score': 1, 'thumbsUpCount': 0, 'reviewCreatedVersion': '1.1.41',
            'at': datetime.datetime(2022, 4, 3, 20, 18, 8),
            'replyContent': 'Hi Vivek, We are working to give you a better experience in next upgrade. Stay tuned! Do not share your account no. & card details such as card number, CVV, expiry and PIN, mobile app & internet banking login credentials with anyone. Happy Banking! Team BOI',
            'repliedAt': datetime.datetime(2022, 3, 28, 7, 53, 44)}, source_name='PlayStoreScrapper',
                                                                                         processed_text="At least provide basic features of updating email id, Contact number online. Your Server Automatically deleted my email, Now you want me to take one leave and visit to branch for your mistake. Then what's the use of your this app and netbanking. Even small fintech mashroomed have better apps than BOI. Banks backend team's work is not merely to do task, but to check and ensure the effectiveness of performed tasks/Adequacy of provided options and adding more &more convenience to customers."),
        TextPayload(segmented_data={}, meta={
            'reviewId': 'gp:AOqpTOGWIfkODM6v_sh60Hp1j2d_S8kRe8vHbXMJGvaTn_tPKDNX8pMiHQT8iGAChdDaS_zamwooil-_jczaEkc',
            'userName': 'Hasmukh Shah',
            'userImage': 'https://play-lh.googleusercontent.com/a/AATXAJzLhEtmJrILJNqBXG79cZdns373OhVHBzaPaT5U=mo',
            'content': 'Nice services', 'score': 5, 'thumbsUpCount': 0, 'reviewCreatedVersion': '1.1.41',
            'at': datetime.datetime(2022, 4, 2, 14, 9, 12), 'replyContent': None, 'repliedAt': None},
                    source_name='PlayStoreScrapper', processed_text='Nice services'), TextPayload(segmented_data={},
                                                                                                  meta={
                                                                                                      'reviewId': 'gp:AOqpTOHdyMBdG3te4-egDs1eQ080DiXLz3rezyQgQa464EK4zn89qAk042ak1-S3dMcTfiEQQtyd1Gz31i7oB5c',
                                                                                                      'userName': 'NIKHIL SATAM',
                                                                                                      'userImage': 'https://play-lh.googleusercontent.com/a-/AOh14GhenuyqGlH6gUJUEVPcgv-sdcDZXFIMaZ0sTjvk',
                                                                                                      'content': 'Unable to go to Home screen once you enter into UPI page.',
                                                                                                      'score': 3,
                                                                                                      'thumbsUpCount': 0,
                                                                                                      'reviewCreatedVersion': '1.1.41',
                                                                                                      'at': datetime.datetime(
                                                                                                          2022, 4,
                                                                                                          1, 11, 22,
                                                                                                          21),
                                                                                                      'replyContent': None,
                                                                                                      'repliedAt': None},
                                                                                                  source_name='PlayStoreScrapper',
                                                                                                  processed_text='Unable to go to Home screen once you enter into UPI page.'),
        TextPayload(segmented_data={}, meta={
            'reviewId': 'gp:AOqpTOGkKjMQity05ai5JKtj48YIYlZUGQllooN54E8X6tul1yvJndi6fq3RVv2V5tL6-7pyk9XOvbYK8R4LHI8',
            'userName': 'Supriya Kumari',
            'userImage': 'https://play-lh.googleusercontent.com/a-/AOh14Ghif2Lb3hfbRBXXnlSVAFPdmijXWSTkV4wdetpk1w',
            'content': 'How to login in this app', 'score': 1, 'thumbsUpCount': 0, 'reviewCreatedVersion': '1.1.41',
            'at': datetime.datetime(2022, 3, 31, 11, 17, 47), 'replyContent': None, 'repliedAt': None},
                    source_name='PlayStoreScrapper', processed_text='How to login in this app'),
        TextPayload(segmented_data={}, meta={
            'reviewId': 'gp:AOqpTOHYiNGr9zZZ9wzSmhweryjQALJLsbFJEAl0JFEOrQSSgoCnp2cx4eh0ENjDD0HCevBt9J1tqsn7fspYm_E',
            'userName': 'AvTaR',
            'userImage': 'https://play-lh.googleusercontent.com/a-/AOh14GhYIq68v3eaiVDezpEWEyevbHSqq5OXxW_v6hR9wA',
            'content': 'Nice app', 'score': 5, 'thumbsUpCount': 0, 'reviewCreatedVersion': '1.1.40',
            'at': datetime.datetime(2022, 3, 29, 23, 5, 40), 'replyContent': None, 'repliedAt': None},
                    source_name='PlayStoreScrapper', processed_text='Nice app'), TextPayload(segmented_data={},
                                                                                             meta={
                                                                                                 'reviewId': 'gp:AOqpTOEFjAIvtA-IOBTSlpl_DCF_Nv-9gJ3mNJLpOGO7EQBpj-ch9oj20QfpmIzK7clRLv4uc9cZe9S6j4TWunY',
                                                                                                 'userName': 'jitu jadhav',
                                                                                                 'userImage': 'https://play-lh.googleusercontent.com/a-/AOh14Gh1bUIHQWF7ZzYA6Q8RJZwRMiJOAk7SbfAdp51r9A',
                                                                                                 'content': 'BETTER',
                                                                                                 'score': 5,
                                                                                                 'thumbsUpCount': 0,
                                                                                                 'reviewCreatedVersion': '1.1.40',
                                                                                                 'at': datetime.datetime(
                                                                                                     2022, 3, 29,
                                                                                                     16, 54, 26),
                                                                                                 'replyContent': None,
                                                                                                 'repliedAt': None},
                                                                                             source_name='PlayStoreScrapper',
                                                                                             processed_text='BETTER'),
        TextPayload(segmented_data={}, meta={
            'reviewId': 'gp:AOqpTOEznTgxo7X6MZqeZ06kbcnFWLQeIjM5dhkwr4Izvlsi00hzTPPCQ8ovyPVLU8RLDglfsncgDsTBDOKry1o',
            'userName': 'swayam vikash patra',
            'userImage': 'https://play-lh.googleusercontent.com/a-/AOh14GjtWlXLYy7KoCqg7vvVLdyyG6IAVL69bg7rmx3ntg',
            'content': 'it is easy to use the UPI system in BOI mobile apps', 'score': 5, 'thumbsUpCount': 1,
            'reviewCreatedVersion': '1.1.41', 'at': datetime.datetime(2022, 3, 29, 13, 56, 26),
            'replyContent': 'Hi swayam vikash patra, We are delighted that you liked our app. Do not share your account no. & card details such as card number, CVV, expiry and PIN, mobile app & internet banking login credentials with anyone. Happy Banking! Team BOI',
            'repliedAt': datetime.datetime(2022, 4, 1, 12, 42, 12)}, source_name='PlayStoreScrapper',
                    processed_text='it is easy to use the UPI system in BOI mobile apps'),
        TextPayload(segmented_data={}, meta={
            'reviewId': 'gp:AOqpTOHf_wHPr6W_kR2cWWo5KXlQtOuMlcHH8rtSSG_nWlTUm_y_yVPZeLOsfJ3fBqqgFJP3zXnYsQAnTmYmn0A',
            'userName': 'Anil Kumar Panigrahi',
            'userImage': 'https://play-lh.googleusercontent.com/a/AATXAJwvC2k00ST5kCe9AOmgBUM_QJiwytuqcuYXUMe3OQ=mo',
            'content': 'Wonderful Experience', 'score': 5, 'thumbsUpCount': 0, 'reviewCreatedVersion': None,
            'at': datetime.datetime(2022, 3, 29, 13, 22, 44),
            'replyContent': 'Hi Anil Kumar Panigrahi, We are delighted that you liked our app. Do not share your account no. & card details such as card number, CVV, expiry and PIN, mobile app & internet banking login credentials with anyone. Happy Banking! Team BOI',
            'repliedAt': datetime.datetime(2022, 4, 1, 10, 32, 6)}, source_name='PlayStoreScrapper',
                    processed_text='Wonderful Experience'), TextPayload(segmented_data={}, meta={
            'reviewId': 'gp:AOqpTOGcqMgsW1RWGA6jfC2MjaZBJ1XzTGNsS_-2yA_PNq99SxBa5gaugKVk3BXAQdcwQBZ6EOQ7DA8pEdOUiDw',
            'userName': 'Hitesh Poptani',
            'userImage': 'https://play-lh.googleusercontent.com/a/AATXAJxhhd63BmwxlcX9QIDeKat8iBfag2970mR6qda1=mo',
            'content': 'No option to give you- rating any customer account is not safe in this bank without your permission they debit your account and your account is minus',
            'score': 1, 'thumbsUpCount': 0, 'reviewCreatedVersion': '1.1.41',
            'at': datetime.datetime(2022, 3, 28, 18, 35, 9),
            'replyContent': 'Hi Hitesh Poptani, We are working to give you a better experience in next upgrade. Stay tuned! Do not share your account no. & card details such as card number, CVV, expiry and PIN, mobile app & internet banking login credentials with anyone. Happy Banking! Team BOI',
            'repliedAt': datetime.datetime(2022, 4, 1, 9, 1, 3)}, source_name='PlayStoreScrapper',
                                                                        processed_text='No option to give you- rating any customer account is not safe in this bank without your permission they debit your account and your account is minus'),
        TextPayload(segmented_data={}, meta={
            'reviewId': 'gp:AOqpTOGenUJIascL2O9nCxwQoidSc4tX4FJC-rcuT6jFj2lfXLDjCcgvRbxzvT3LA7Z532XVy1DztdDlPETdRQ0',
            'userName': 'KUNAL KUMAR',
            'userImage': 'https://play-lh.googleusercontent.com/a/AATXAJwJObMN-GYEBmJLEDV59_EqWFAM21VgQK6VISFh=mo',
            'content': 'User friendly', 'score': 5, 'thumbsUpCount': 0, 'reviewCreatedVersion': '1.1.41',
            'at': datetime.datetime(2022, 3, 28, 8, 41, 14),
            'replyContent': 'Hi KUNAL KUMAR, We are delighted that you liked our app. Do not share your account no. & card details such as card number, CVV, expiry and PIN, mobile app & internet banking login credentials with anyone. Happy Banking! Team BOI',
            'repliedAt': datetime.datetime(2022, 3, 28, 7, 59, 45)}, source_name='PlayStoreScrapper',
                    processed_text='User friendly'), TextPayload(segmented_data={}, meta={
            'reviewId': 'gp:AOqpTOFDrVssEkUUMe8Eskl2uragN1ElyvQOSgCIyljMht6dK9hzJggWajbf5HwglBOyiOBJC3Q_L4VvOOLiA3o',
            'userName': 'Bhargavi Patil',
            'userImage': 'https://play-lh.googleusercontent.com/a/AATXAJyozSAWkQHuCtPjLu4eLtcEhy1M-eiif4jfkwZF=mo',
            'content': 'Very good app', 'score': 5, 'thumbsUpCount': 0, 'reviewCreatedVersion': '1.1.40',
            'at': datetime.datetime(2022, 3, 27, 16, 39, 23),
            'replyContent': 'Hi Bhargavi Patil, We are delighted that you liked our app. Do not share your account no. & card details such as card number, CVV, expiry and PIN, mobile app & internet banking login credentials with anyone. Happy Banking! Team BOI',
            'repliedAt': datetime.datetime(2022, 3, 27, 16, 51, 33)}, source_name='PlayStoreScrapper',
                                                                 processed_text='Very good app'),
        TextPayload(segmented_data={}, meta={
            'reviewId': 'gp:AOqpTOGz8VSA7wKCwMUShHIUlv9gkUD8yGGsYUVkkOwXjD5S_lKsLhBKYsCDH5uVTodac4xOXARxrchVa1PdzOE',
            'userName': 'harneet singh',
            'userImage': 'https://play-lh.googleusercontent.com/a-/AOh14GjV976A803lsQSY0sPICSfH3cSc_gMMxgPUlUVL',
            'content': 'Not working', 'score': 1, 'thumbsUpCount': 0, 'reviewCreatedVersion': '1.1.41',
            'at': datetime.datetime(2022, 3, 27, 10, 49, 20),
            'replyContent': 'Hi harneet singh, We are working to give you a better experience in next upgrade. Stay tuned! Do not share your account no. & card details such as card number, CVV, expiry and PIN, mobile app & internet banking login credentials with anyone. Happy Banking! Team BOI',
            'repliedAt': datetime.datetime(2022, 3, 9, 17, 46, 45)}, source_name='PlayStoreScrapper',
                    processed_text='Not working'), TextPayload(segmented_data={}, meta={
            'reviewId': 'gp:AOqpTOEBEbgiCRa1-Kwsy8DIjBlUdNlDG43REXSaCZFObqg9M29R293Bu4INmSXCN-LlCqojG1DFrVYY16cbU1I',
            'userName': 'Ramarao Pilli8',
            'userImage': 'https://play-lh.googleusercontent.com/a/AATXAJwebWyACnQh37kYTX1TQXFjhhn7a7Hugh75URpa=mo',
            'content': 'Our transanctions are succesful through mobile phone.', 'score': 5, 'thumbsUpCount': 1,
            'reviewCreatedVersion': '1.1.41', 'at': datetime.datetime(2022, 3, 26, 19, 23, 7),
            'replyContent': 'Hi Ramarao Pilli8, We are delighted that you liked our app. Do not share your account no. & card details such as card number, CVV, expiry and PIN, mobile app & internet banking login credentials with anyone. Happy Banking! Team BOI',
            'repliedAt': datetime.datetime(2022, 3, 27, 9, 31, 10)}, source_name='PlayStoreScrapper',
                                                               processed_text='Our transanctions are succesful through mobile phone.'),
        TextPayload(segmented_data={}, meta={
            'reviewId': 'gp:AOqpTOHllD-Cq7LsiNjCFKbIVfBPHfrbeFg-s8WlSIFTx_9g0jFkpKVqQu9V902g2AUGGo8vDJPYqBsGsUt4TnE',
            'userName': 'Bhavya Mehta',
            'userImage': 'https://play-lh.googleusercontent.com/a/AATXAJzwgn9ScIaS87XDyMfZxqTb1peipaneaRzz8LJt=mo',
            'content': "App takes a lot of time to load; it's such a time waste. Also, after filling the credentials to Log in it still shows validating and still opens it.",
            'score': 1, 'thumbsUpCount': 0, 'reviewCreatedVersion': '1.1.40',
            'at': datetime.datetime(2022, 3, 26, 15, 15, 28),
            'replyContent': 'Hi, We regret inconvenience caused to you. Please share your customer id, registered mobile number and the issue faced at support.digitalapps@bankofindia.co.in so that we can assist you. Do not share your account no. & card details such as card number, CVV, expiry and PIN, mobile app & internet banking login credentials with anyone. Happy Banking!',
            'repliedAt': datetime.datetime(2022, 3, 27, 15, 41, 14)}, source_name='PlayStoreScrapper',
                    processed_text="App takes a lot of time to load; it's such a time waste. Also, after filling the credentials to Log in it still shows validating and still opens it."),
        TextPayload(segmented_data={}, meta={
            'reviewId': 'gp:AOqpTOHEzQlWh6HNscRlu8iCZrc8tHufsm4CLKNVxdi_YoGC3hg9OQUeDkkfGzbySScS8C554Y8AsUAxab6QmqA',
            'userName': 'Abhishek Kumar',
            'userImage': 'https://play-lh.googleusercontent.com/a/AATXAJzWuKlAx7scGokvndUOLnHFWZvgCqS1tLahRxPP=mo',
            'content': 'Good work', 'score': 4, 'thumbsUpCount': 0, 'reviewCreatedVersion': '1.1.41',
            'at': datetime.datetime(2022, 3, 26, 11, 37, 26),
            'replyContent': 'Hi Abhishek Kumar, We are delighted that you liked our app. Do not share your account no. & card details such as card number, CVV, expiry and PIN, mobile app & internet banking login credentials with anyone. Happy Banking! Team BOI',
            'repliedAt': datetime.datetime(2022, 3, 27, 14, 42, 50)}, source_name='PlayStoreScrapper',
                    processed_text='Good work'), TextPayload(segmented_data={}, meta={
            'reviewId': 'gp:AOqpTOH9MWnQHlYZyCVlPu7RmJMNs96Yzhh0cRtiS9LjYaooFHWd17VL8H4fzeVnPyf7UBTIjI8RQHo-f4srMvc',
            'userName': 'Sampada Duduskar',
            'userImage': 'https://play-lh.googleusercontent.com/a-/AOh14Giud9wG9ZyLYi5-9EhJMieJtvfJll0gizlaRanHTg',
            'content': 'Very nice app', 'score': 5, 'thumbsUpCount': 0, 'reviewCreatedVersion': '1.1.41',
            'at': datetime.datetime(2022, 3, 26, 8, 58, 24),
            'replyContent': 'Hi Sampada Duduskar, We are delighted that you liked our app. Do not share your account no. & card details such as card number, CVV, expiry and PIN, mobile app & internet banking login credentials with anyone. Happy Banking! Team BOI',
            'repliedAt': datetime.datetime(2022, 3, 27, 9, 34, 52)}, source_name='PlayStoreScrapper',
                                                             processed_text='Very nice app'),
        TextPayload(segmented_data={}, meta={
            'reviewId': 'gp:AOqpTOEqzfbTFwJJ-ekN_spiWt9OVGYqZ39z4TUcuugI88pMWHHwqLyNQg7S5iT97Bc625NyNaf2b5_jpamvmPQ',
            'userName': 'Suresh Talaviya',
            'userImage': 'https://play-lh.googleusercontent.com/a-/AOh14Gh0lRXGoyqZVpfYG_86nh62iFJEwxV-bHfUC7bCHw',
            'content': 'Easy to use I like it', 'score': 5, 'thumbsUpCount': 0, 'reviewCreatedVersion': '1.1.41',
            'at': datetime.datetime(2022, 3, 26, 6, 25, 20),
            'replyContent': 'Hi Suresh Talaviya, We are delighted that you liked our app. Do not share your account no. & card details such as card number, CVV, expiry and PIN, mobile app & internet banking login credentials with anyone. Happy Banking! Team BOI',
            'repliedAt': datetime.datetime(2022, 3, 26, 10, 21, 26)}, source_name='PlayStoreScrapper',
                    processed_text='Easy to use I like it')]
