version: '3'
services:
  api-service-local:
    image: api-service-local
    environment:
      - DB_HOST=host.docker.internal:5432
      - CORE_DB_USER=girish
      - CORE_DB_PASSWORD=girish
      - PREFECT_DB_USER=girish
      - PREFECT_DB_NAME=prefect_local
      - PREFECT_DB_PASSWORD=girish
      - PREFECT_API_URL=http://127.0.0.1:4200/api
      - OPENAI_API_KEY=xsdfex
      - OUTSCRAPPER_API_KEY=styhbgfds
      - SPACEPULSE_URL=http://host.docker.internal:3001/capAm/enquiry/partner
      - SPACEPULSE_API_KEY=dummykey
      - SPACEPULSE_API_SECRET=dummaysecret
    ports:
      - "4200:4200"
      - "8080:8080"
    network_mode: "bridge"
    extra_hosts:
      - "host.docker.internal:host-gateway"
