name: CI Job

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Build"
        run: |
          set -e
          set -x
          python3 -m pip install mypy
          make svc-observer-dep svc-analyzer-dep svc-api-dep
          make svc-observer-dev svc-analyzer-dev svc-api-dev
          make mypy-analyse
          make tnt-onboarding-build
