name: CI Job

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: "Build"
        run: |
          set -e
          set -x
          yarn

          # yarn workspace orb add jest-environment-jsdom
          yarn workspace orb build
