import datetime

from obsei.payload import TextPayload


def get_ios_payload():
    return [TextPayload(segmented_data={},
                        meta={'version': '3.81.0', 'rating': 5, 'id': 8512151025, 'title': '@Retired_pablo',
                              'date': datetime.datetime(2022, 3, 30, 14, 1, 5),
                              'author_link': 'https://itunes.apple.com/us/reviews/id1297758134',
                              'author_name': 'retiredpablo', 'country': 'us', 'vote_count': 0, 'vote_sum': 0},
                        source_name='AppStoreScrapper',
                        processed_text='@Retired_pablo. Well there isnâ€™t much to say when you are confident with this app. There services are top notch. Deliver your money within seconds when using skrill to skrill. I havenâ€™t had any problem with it before and yet they havenâ€™t given me any doubt or any issue that result to any form of any problem. My money is always safe with skrill. Fast, reliable and secure as it should be. @Retired_pablo'),
            TextPayload(segmented_data={},
                        meta={'version': '3.81.0', 'rating': 1, 'id': 8506145509, 'title': 'Bad support. Bad app',
                              'date': datetime.datetime(2022, 3, 28, 20, 40, 47),
                              'author_link': 'https://itunes.apple.com/us/reviews/id381978227',
                              'author_name': 'DarkWinterYt', 'country': 'us', 'vote_count': 0, 'vote_sum': 0},
                        source_name='AppStoreScrapper',
                        processed_text='Bad support. Bad app. I was trying to use Skrill to transfer funds. But it will not let me withdraw the funds. And when I contact support they keep giving me the run around.  They are not a very good app and Iâ€™m so upset that I decided to use Skrill'),
            TextPayload(segmented_data={},
                        meta={'version': '3.81.0', 'rating': 1, 'id': 8500326675, 'title': 'Deposits',
                              'date': datetime.datetime(2022, 3, 27, 6, 26, 39),
                              'author_link': 'https://itunes.apple.com/us/reviews/id1363505093',
                              'author_name': 'briuanna1', 'country': 'us', 'vote_count': 0, 'vote_sum': 0},
                        source_name='AppStoreScrapper',
                        processed_text='Deposits. I donâ€™t understand why it takes so long after clearing my bank to receive a bank wire transfer? I made 3 deposits within 24 hours and that was on the 22nd going into the 23rd I finally received access to one of those deposits earlier today the 26th and going into the 27th now I still have yet to receive the other two deposits. When I tried contacting them via messaging, I didnâ€™t get a response the ticket was just marked as resolved until I addressed that as well and then I was still told after 5 days then reach back out to them. That is ridiculous..'),
            TextPayload(segmented_data={}, meta={'version': '3.81.0', 'rating': 5, 'id': 8491692148,
                                                 'title': 'Please and Nigeria bank transfer to deposit',
                                                 'date': datetime.datetime(2022, 3, 24, 22, 22, 55),
                                                 'author_link': 'https://itunes.apple.com/us/reviews/id1328120243',
                                                 'author_name': 'blessinbp', 'country': 'us', 'vote_count': 0,
                                                 'vote_sum': 0}, source_name='AppStoreScrapper',
                        processed_text='Please and Nigeria bank transfer to deposit. Nigeria canâ€™t deposit to their Skrill or netteller account with Nigeria card is not working please help us Nigeria is either you guys collect bank transfer NGN'),
            TextPayload(segmented_data={}, meta={'version': '3.81.0', 'rating': 5, 'id': 8491036889,
                                                 'title': 'Skrill is the best way you can Send money internationally and manage my Cryptocurrency',
                                                 'date': datetime.datetime(2022, 3, 24, 17, 39, 7),
                                                 'author_link': 'https://itunes.apple.com/us/reviews/id1263198333',
                                                 'author_name': 'trixykeks', 'country': 'us', 'vote_count': 0,
                                                 'vote_sum': 0}, source_name='AppStoreScrapper',
                        processed_text='Skrill is the best way you can Send money internationally and manage my Cryptocurrency. Iâ€™ve been using Skrill for several years already and Skrill never fail me. Itâ€™s the best way you can keep your money securely and manage your crypto currency â�¤ï¸� Twitter @Jasfawler1'),
            TextPayload(segmented_data={},
                        meta={'version': '3.81.0', 'rating': 4, 'id': 8483933450, 'title': 'Very Good',
                              'date': datetime.datetime(2022, 3, 22, 17, 15, 10),
                              'author_link': 'https://itunes.apple.com/us/reviews/id700515208', 'author_name': 'im saa',
                              'country': 'us', 'vote_count': 0, 'vote_sum': 0}, source_name='AppStoreScrapper',
                        processed_text='Very Good. @zazahovic'), TextPayload(segmented_data={},
                                                                             meta={'version': '3.81.0', 'rating': 1,
                                                                                   'id': 8479717034,
                                                                                   'title': 'Skrill card',
                                                                                   'date': datetime.datetime(2022, 3,
                                                                                                             21, 12, 30,
                                                                                                             55),
                                                                                   'author_link': 'https://itunes.apple.com/us/reviews/id1093278246',
                                                                                   'author_name': 'lenasps5',
                                                                                   'country': 'us', 'vote_count': 0,
                                                                                   'vote_sum': 0},
                                                                             source_name='AppStoreScrapper',
                                                                             processed_text='Skrill card. Why people from North Africa canâ€™t get Skrill card ? Shame on you'),
            TextPayload(segmented_data={},
                        meta={'version': '3.81.0', 'rating': 1, 'id': 8477661660, 'title': 'Pathetic',
                              'date': datetime.datetime(2022, 3, 20, 21, 26, 2),
                              'author_link': 'https://itunes.apple.com/us/reviews/id1237951113',
                              'author_name': 'swayned75', 'country': 'us', 'vote_count': 0, 'vote_sum': 0},
                        source_name='AppStoreScrapper',
                        processed_text='Pathetic. Iâ€™ve had a Skrill. Account for over a year and out of the blue they want me to verify myself, no big deal right? \nThe biggest deal Iâ€™ve ever had with any online money. They basically have stolen my money.  \nIâ€™ve sent the photos of my documents ( ID, proof of address my Skrill debit card and every time, thereâ€™s a problem. Either itâ€™s too shiny or too dark. Iâ€™ve sent these items 18 times. After the 10th time I knew something wasnâ€™t right so I kept resubmitting the same picture and as I suspected, they came back with a different reason why. It wasnâ€™t acceptable.  How can the same picture be too shiny and too dark and too blurry or the picture is too big! When itâ€™s the same picture!!!!!\n Itâ€™s been 2 months since this game has started. They even sent me a new Skrill debit card. So that explains the intelligence. Professionalism of the Skrill security/support members. \nAn awful lot of work to keep my $150.00'),
            TextPayload(segmented_data={},
                        meta={'version': '3.81.0', 'rating': 5, 'id': 8471075125, 'title': 'IG : Ppanther_5',
                              'date': datetime.datetime(2022, 3, 19, 4, 21, 53),
                              'author_link': 'https://itunes.apple.com/us/reviews/id1183006829',
                              'author_name': 'ppanther 1996', 'country': 'us', 'vote_count': 0, 'vote_sum': 0},
                        source_name='AppStoreScrapper', processed_text='IG : Ppanther_5. Amazing app love it ğŸ˜�'),
            TextPayload(segmented_data={},
                        meta={'version': '3.81.0', 'rating': 5, 'id': 8469022636, 'title': 'Skrill Review',
                              'date': datetime.datetime(2022, 3, 18, 14, 47, 51),
                              'author_link': 'https://itunes.apple.com/us/reviews/id1164514849',
                              'author_name': 'thejamesnick', 'country': 'us', 'vote_count': 0, 'vote_sum': 0},
                        source_name='AppStoreScrapper',
                        processed_text='Skrill Review. Skrill as been a very useful platform for me for a year now.\nFrom receiving payment from client, to spending and to saving.\nI donâ€™t know what I will do without Skrill. Thanks so much for this Opportunity. @thejamesnicks'),
            TextPayload(segmented_data={}, meta={'version': '3.80.0', 'rating': 1, 'id': 8465953580, 'title': 'Theives',
                                                 'date': datetime.datetime(2022, 3, 17, 17, 41, 54),
                                                 'author_link': 'https://itunes.apple.com/us/reviews/id1385007753',
                                                 'author_name': 'monday2222', 'country': 'us', 'vote_count': 0,
                                                 'vote_sum': 0}, source_name='AppStoreScrapper',
                        processed_text='Theives. You all allowed me to send 208$ to my skrill you didnâ€™t ask for verification itâ€™s till I sent money to the account you restricted and I provided all the necessary document but you keep rejecting And now you permanently closed the account meaning I canâ€™t get my money back go will punish you guys you are just theives nothing but thieves no flexibility at all I ensure nobody download this app for their safety now I am left with nothing \nThieves...you all are thieves \n\nI wish I never rated but I will to get my message to you'),
            TextPayload(segmented_data={}, meta={'version': '3.80.0', 'rating': 1, 'id': 8455622717,
                                                 'title': 'Scam - Used my email address without permission, unable to cancel acclunt',
                                                 'date': datetime.datetime(2022, 3, 14, 18, 45, 50),
                                                 'author_link': 'https://itunes.apple.com/us/reviews/id129421639',
                                                 'author_name': 'Leinad big', 'country': 'us', 'vote_count': 0,
                                                 'vote_sum': 0}, source_name='AppStoreScrapper',
                        processed_text='Scam - Used my email address without permission, unable to cancel acclunt. Apple please consider removing skrill. I did not create account. Used email email without permission and will not cancel account'),
            TextPayload(segmented_data={}, meta={'version': '3.80.0', 'rating': 5, 'id': 8442643784,
                                                 'title': 'Me encanta esta buena y funciona',
                                                 'date': datetime.datetime(2022, 3, 11, 5, 5, 40),
                                                 'author_link': 'https://itunes.apple.com/us/reviews/id715602748',
                                                 'author_name': 'melquisedec1001', 'country': 'us', 'vote_count': 0,
                                                 'vote_sum': 0}, source_name='AppStoreScrapper',
                        processed_text='Me encanta esta buena y funciona. Funciona bien'),
            TextPayload(segmented_data={},
                        meta={'version': '3.80.0', 'rating': 1, 'id': 8423614357, 'title': 'They just steal my money',
                              'date': datetime.datetime(2022, 3, 5, 15, 55, 57),
                              'author_link': 'https://itunes.apple.com/us/reviews/id960186536',
                              'author_name': 'Gasy tezitra', 'country': 'us', 'vote_count': 0, 'vote_sum': 0},
                        source_name='AppStoreScrapper',
                        processed_text='They just steal my money. As we know, covid19 was forcing people to go home from beginning, so I wasnâ€™t unable to use skrill from my hometown and one year later, checking my found, Skrill just deduct my money of 189$ and they are saying anything stupid to not refund me, \n\nLeave Skrill very far, I regreted to join them')]
