from obsei.payload import TextPayload


def get_twitter_payload():
    return [TextPayload(segmented_data={},
                        meta={'conversation_id': '1510243251323691010', 'created_at': '2022-04-04T09:06:30.000Z',
                              'public_metrics': {'retweet_count': 0, 'reply_count': 0, 'like_count': 0,
                                                 'quote_count': 0}, 'id': '1510906646687784963',
                              'author_id': '378742496', 'author_info': {
                                'public_metrics': {'followers_count': 30, 'following_count': 33, 'tweet_count': 4,
                                                   'listed_count': 1}, 'name': 'Avni', 'verified': False,
                                'id': '378742496', 'username': 'avnidas09',
                                'user_url': 'https://twitter.com/avnidas09'},
                              'tweet_url': 'https://twitter.com/twitter/statuses/1510906646687784963'},
                        source_name='Twitter',
                        processed_text='@sbmbankindia In response to the SR raised, I cannot provide FD details as that is also not working. Screenshot has been shared. Kindly do the needful without playing games of delay.'),
            TextPayload(segmented_data={},
                        meta={'conversation_id': '1503315655340474369', 'created_at': '2022-04-04T08:15:29.000Z',
                              'public_metrics': {'retweet_count': 0, 'reply_count': 0, 'like_count': 0,
                                                 'quote_count': 0}, 'id': '1510893809231572998',
                              'author_id': '900909425665253376', 'author_info': {
                                'public_metrics': {'followers_count': 4083, 'following_count': 3136,
                                                   'tweet_count': 19312, 'listed_count': 2}, 'name': 'K A L K I',
                                'verified': False, 'id': '900909425665253376', 'username': 'iamkalki_13',
                                'user_url': 'https://twitter.com/iamkalki_13'},
                              'tweet_url': 'https://twitter.com/twitter/statuses/1510893809231572998'},
                        source_name='Twitter',
                        processed_text='@sbmbankindia @OneCardHelp @GetOneCardIN Seriously? no customer support at all, tried to contact through mail,social media platforms, customer care numbers..no response at all'),
            TextPayload(segmented_data={},
                        meta={'conversation_id': '1510888125769269252', 'created_at': '2022-04-04T07:52:54.000Z',
                              'public_metrics': {'retweet_count': 0, 'reply_count': 0, 'like_count': 0,
                                                 'quote_count': 0}, 'id': '1510888125769269252',
                              'author_id': '871350225901731841', 'author_info': {
                                'public_metrics': {'followers_count': 7, 'following_count': 28, 'tweet_count': 124,
                                                   'listed_count': 0}, 'name': 'Sajal Mathur', 'verified': False,
                                'id': '871350225901731841', 'username': 'Mathur_saab',
                                'user_url': 'https://twitter.com/Mathur_saab'},
                              'tweet_url': 'https://twitter.com/twitter/statuses/1510888125769269252'},
                        source_name='Twitter',
                        processed_text='@sliceit_ Are are any customer support officials there in your office. The call Never gets through and no response on the repeated emails sent on billing queries. @sbmbankindia guys your reputation is at stake. Disappointing experience.'),
            TextPayload(segmented_data={},
                        meta={'conversation_id': '1510718862010228740', 'created_at': '2022-04-04T06:07:28.000Z',
                              'public_metrics': {'retweet_count': 0, 'reply_count': 0, 'like_count': 0,
                                                 'quote_count': 0}, 'id': '1510861591973093376',
                              'author_id': '2892512942', 'author_info': {
                                'public_metrics': {'followers_count': 5783, 'following_count': 216,
                                                   'tweet_count': 10533, 'listed_count': 23}, 'name': 'Paisabazaar.com',
                                'verified': True, 'id': '2892512942', 'username': 'PaisaBazaar_in',
                                'user_url': 'https://twitter.com/PaisaBazaar_in'},
                              'tweet_url': 'https://twitter.com/twitter/statuses/1510861591973093376'},
                        source_name='Twitter',
                        processed_text='@parmarrakesh3 @sbmbankindia @RBI @FinMinIndia We are concerned by your Tweet and eager to assist you. Kindly share your contact details with us via DM, the relevant team will connect with you shortly and address your concerns. https://t.co/HUtr1JDGDn'),
            TextPayload(segmented_data={},
                        meta={'conversation_id': '1510718862010228740', 'created_at': '2022-04-03T20:40:19.000Z',
                              'public_metrics': {'retweet_count': 0, 'reply_count': 1, 'like_count': 1,
                                                 'quote_count': 0}, 'id': '1510718862010228740',
                              'author_id': '554109249', 'author_info': {
                                'public_metrics': {'followers_count': 12, 'following_count': 228, 'tweet_count': 468,
                                                   'listed_count': 0}, 'name': 'parmar rakesh', 'verified': False,
                                'id': '554109249', 'username': 'parmarrakesh3',
                                'user_url': 'https://twitter.com/parmarrakesh3'},
                              'tweet_url': 'https://twitter.com/twitter/statuses/1510718862010228740'},
                        source_name='Twitter',
                        processed_text='@PaisaBazaar_in @sbmbankindia @RBI @FinMinIndia \nMene 31 March ko credit card ka bill pay kar diya 4999 magar abhi tak update nahi hua to please update my payment fast'),
            TextPayload(segmented_data={},
                        meta={'conversation_id': '1510638916076183560', 'created_at': '2022-04-03T15:22:38.000Z',
                              'public_metrics': {'retweet_count': 0, 'reply_count': 0, 'like_count': 0,
                                                 'quote_count': 0}, 'id': '1510638916076183560',
                              'author_id': '1063366209041661952', 'author_info': {
                                'public_metrics': {'followers_count': 9, 'following_count': 194, 'tweet_count': 72,
                                                   'listed_count': 0}, 'name': 'Rogin George', 'verified': False,
                                'id': '1063366209041661952', 'username': 'georgeeboii',
                                'user_url': 'https://twitter.com/georgeeboii'},
                              'tweet_url': 'https://twitter.com/twitter/statuses/1510638916076183560'},
                        source_name='Twitter',
                        processed_text='@sbmbankindia my UNI credit card is recognized as debit card. 🧐 Could you help https://t.co/0FCdSo3poj'),
            TextPayload(segmented_data={},
                        meta={'conversation_id': '1503315655340474369', 'created_at': '2022-04-03T11:44:57.000Z',
                              'public_metrics': {'retweet_count': 0, 'reply_count': 1, 'like_count': 0,
                                                 'quote_count': 0}, 'id': '1510584134355550213',
                              'author_id': '834653456438874113', 'author_info': {
                                'public_metrics': {'followers_count': 61, 'following_count': 4, 'tweet_count': 193,
                                                   'listed_count': 1}, 'name': 'Mohit Jain', 'verified': False,
                                'id': '834653456438874113', 'username': 'Bhadkaladka',
                                'user_url': 'https://twitter.com/Bhadkaladka'},
                              'tweet_url': 'https://twitter.com/twitter/statuses/1510584134355550213'},
                        source_name='Twitter',
                        processed_text='@sbmbankindia @OneCardHelp @GetOneCardIN @sbmbankindia @OneCardHelp could you check the Dm I’m facing some issues the app is very pathetic')]
